pipeline {
    agent any
    // Deploy application from 3855 VM 
    stage('Deploy'){

    // Only run when deploy param is checked
    

    // Use SSH credentials for key
        steps {
            sshagent(credentials: ['SSH']) {
                sh "ssh -o StrictHostKeyChecking=no -l azureuser 172.178.11.14 'cd ~/acit-3855-lab6/deployment && docker pull penpen7531/${image}:latest && docker-compose up -d'"
            }   
        }
    }
}
